#!/bin/sh
set -e

case "$1" in
  configure)
    mysql --defaults-file=/etc/mysql/debian.cnf -e "INSTALL PLUGIN sphinx SONAME 'ha_sphinx.so';"
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

exit 0
