#!/bin/sh
set -e

case "$1" in
  purge)
    mysql --defaults-file=/etc/mysql/debian.cnf -e "UNINSTALL PLUGIN sphinx;"
    rm -rf /usr/lib/mysql/plugins/ha_sphinx.so
  ;;
  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;
  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

exit 0
